### ISSUE TITLE
样式调整

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/website#61]
建议去掉这个点, 有点冗余   

![image](https://user-images.githubusercontent.com/3922719/112643746-a67af980-8e7f-11eb-8ceb-d149e5aa0c68.png)

**Comment by wssgcg1213** [comment]
代码字体缩小一号, 不显得拥挤
```css
.markdown :not(pre) code {
  font-size: 14px; 
}
```
